apiVersion: v1
kind: Service
metadata:
    name: "bdoexdevcluster04-5a6d"
    labels:
        app: "bdoexdevcluster04-5a6d"
spec:
    type: LoadBalancer
    ports:
    - port: 3317
      targetPort: 3317
      protocol: TCP
      name: http
    selector:
        app: "bdoexdevcluster04-5a6d"